# Generated by Django 5.2.3 on 2025-06-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturasensor',
            old_name='timestamp',
            new_name='fecha',
        ),
        migrations.AddField(
            model_name='lecturasensor',
            name='TVOC',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lecturasensor',
            name='eCO2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lecturasensor',
            name='humidity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lecturasensor',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lecturasensor',
            name='sensor_id',
            field=models.CharField(max_length=100),
        ),
    ]
