# Generated by Django 5.2.3 on 2025-06-27 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0002_rename_timestamp_lecturasensor_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturasensor',
            old_name='fecha',
            new_name='timestamp',
        ),
    ]
